### ISSUE TITLE
Support concurrent pappy instances using the same proxy

### ISSUE THREAD

**Issue by Holzhaus** [roglew/pappy-proxy#12]
When using a macro to fuzz a webapp, users have to wait until the macro is completed and can't test other parts of the webapp.

It is desireable to run a second pappy instance without the proxy that accesses the state of the first instance. Currently a error message is thrown (since the second pappy instance tries to start the proxy and rebind the port that the proxy of the first pappy instance is already using) and the request list is not updated (e.g. when using `ls` or `watch`).

The alternative solution would be to allow minimizing running macros to background, but I'd prefer the former since that'd also allow multiplexing via tmux or tiling WMs, etc.

**Comment by roglew** [comment]
Hey, sorry for the (really) late response. The next version of pappy is going to separate the proxy/storage functions to a separate process which can handle multiple instances of pappy at the same time. So hopefully the next version will be able to to exactly what you're asking

**Comment by roglew** [comment]
Hey, I just wanted to give you an update to let you know you should be able to do this now, but it's a bit hacky. The current version of pappy interfaces with a running instance of [puppy](https://github.com/roglew/puppy), and supports connecting to an existing puppy process. What you can do is run the `puppy` binary in `~/.pappy` with the `--msgauto` flag. It'll print out an address which you can copy and pass to pappy with the `--attach` flag. As an example:

```
# In terminal window 1:
$ ~/.pappy/puppy --msgauto
unix:/var/folders/b1/g0r3h9jn28xd064rdxq_6q6h0000gp/T//proxy.2529.1499798194507728315.sock

# In terminal window 2, 3, etc:
$ pappy --attach "unix:/var/folders/b1/g0r3h9jn28xd064rdxq_6q6h0000gp/T//proxy.2529.1499798194507728315.sock"
```

Honestly I just use it for debugging sometimes so there are probably bugs, and you're  responsible for killing the puppy process. If you think it'd be an especially useful feature I can work on making it easier to use, but this hacky method should work.
