### ISSUE TITLE
TUI interface (e.g. curses)

### ISSUE THREAD

**Issue by Holzhaus** [roglew/pappy-proxy#14]
I'd really love if this tool had a TUI interface (e.g.  using curses/[urwid](http://urwid.org/examples/index.html)/[npyscreen](http://www.npcole.com/npyscreen/)) for browsing requests and sending them to the repeater, etc.

Would something like this be in scope of this project?

**Comment by roglew** [comment]
It's something that I have thought about, but I have never written a curses interface before. The console interface that exists right now offers a decent enough interface, and I'm afraid that if I try and implement a curses interface I may just introduce bugs and make things worse. If I find myself with some curses experience in the future I may give it a shot. Thanks for the suggestion though!
