### ISSUE TITLE
Add "Burp Active Scanner"-like function

### ISSUE THREAD

**Issue by Holzhaus** [roglew/pappy-proxy#15]
The Burp Active Scanner is quite useful for finding issues and testing webapps for potential weaknesses automatically. Also, using Burps intruder to mark insertion points and then chosing "actively scan defined insertion points" is also neat.

Pappy is currently missing such a feature.

**Comment by roglew** [comment]
Hey, sorry for the late response. This is a feature that I would like to have in the future, but unfortunately this involves maintaining a list of issues to scan for and scripts to check for those issues which is a lot of work for a single developer. It is possible that pappy may support some sort of hooks for other people to implement scanning for issues, but this is a feature that is just a bit much for me as a solo developer. Thank you for the suggestion though!
