### ISSUE TITLE
Pip install missing argument

### ISSUE THREAD

**Issue by Occupy4Elephants** [roglew/pappy-proxy#17]
Installation

Pappy supports OS X and Linux (sorry Windows). Installation requires pip or some other command that can handle a setup.py with requirements. Once the requirements are installed, you can check that it installed correctly by running pappy -l to start the proxy.

$ git clone --recursive https://github.com/roglew/pappy-proxy.git
$ cd pappy-proxy
$ pip install .

^^^ pip install what?

**Comment by AdamSloggett** [comment]
There is a period after the install.  

https://pip.pypa.io/en/stable/reference/pip_install/

**Comment by roglew** [comment]
sorry for the late response! Adam is right, you want to run `pip install .` which will install the package in the `pappy-proxy` directory
